I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 388, in script
    window show
  File "renpy/common/000window.rpy", line 159, in execute_window_show
    _window_show(trans)
  File "renpy/common/000window.rpy", line 69, in _window_show
    renpy.with_statement(trans)
IOError: Couldn't find file 'gui/ddlc/nnb/My Feelings.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 388, in script
    window show
  File "C:\Users\ferro\Desktop\SI UMN\VN Code\renpy-7.4.10-sdk/renpy/ast.py", line 2015, in execute
    self.call("execute")
  File "C:\Users\ferro\Desktop\SI UMN\VN Code\renpy-7.4.10-sdk/renpy/ast.py", line 2003, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\ferro\Desktop\SI UMN\VN Code\renpy-7.4.10-sdk/renpy/statements.py", line 278, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000window.rpy", line 159, in execute_window_show
    _window_show(trans)
  File "renpy/common/000window.rpy", line 69, in _window_show
    renpy.with_statement(trans)
  File "C:\Users\ferro\Desktop\SI UMN\VN Code\renpy-7.4.10-sdk/renpy/exports.py", line 1684, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\ferro\Desktop\SI UMN\VN Code\renpy-7.4.10-sdk/renpy/display/core.py", line 2762, in do_with
    clear=clear)
  File "C:\Users\ferro\Desktop\SI UMN\VN Code\renpy-7.4.10-sdk/renpy/display/core.py", line 3325, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "C:\Users\ferro\Desktop\SI UMN\VN Code\renpy-7.4.10-sdk/renpy/display/core.py", line 4025, in interact_core
    renpy.audio.audio.periodic()
  File "C:\Users\ferro\Desktop\SI UMN\VN Code\renpy-7.4.10-sdk/renpy/audio/audio.py", line 1162, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "C:\Users\ferro\Desktop\SI UMN\VN Code\renpy-7.4.10-sdk/renpy/audio/audio.py", line 1140, in periodic_thread_main
    periodic_pass()
  File "C:\Users\ferro\Desktop\SI UMN\VN Code\renpy-7.4.10-sdk/renpy/audio/audio.py", line 1082, in periodic_pass
    c.periodic()
  File "C:\Users\ferro\Desktop\SI UMN\VN Code\renpy-7.4.10-sdk/renpy/audio/audio.py", line 518, in periodic
    topf = load(filename)
  File "C:\Users\ferro\Desktop\SI UMN\VN Code\renpy-7.4.10-sdk/renpy/audio/audio.py", line 69, in load
    rv = renpy.loader.load(fn)
  File "C:\Users\ferro\Desktop\SI UMN\VN Code\renpy-7.4.10-sdk/renpy/loader.py", line 798, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'gui/ddlc/nnb/My Feelings.mp3'.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
koor_prep 1.0
Sun Jul 10 23:21:22 2022
